#############################################################################
# Makefile for building: qeodart
# Generated by qmake (3.0) (Qt 5.3.0)
# Project:  QeoDart.pro
# Template: app
# Command: /usr/lib/i386-linux-gnu/qt5/bin/qmake -o Makefile QeoDart.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I. -I. -Icpp -isystem /usr/include/i386-linux-gnu/qt5 -isystem /usr/include/i386-linux-gnu/qt5/QtWidgets -isystem /usr/include/i386-linux-gnu/qt5/QtXml -isystem /usr/include/i386-linux-gnu/qt5/QtGui -isystem /usr/include/i386-linux-gnu/qt5/QtCore -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Widgets -L/usr/lib/i386-linux-gnu -lQt5Xml -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/i386-linux-gnu/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = cpp/dart.cpp \
		cpp/io.cpp \
		cpp/main.cpp \
		cpp/qtwin.cpp \
		cpp/preferences.cpp \
		cpp/results.cpp \
		cpp/highscores.cpp \
		cpp/about.cpp qrc_icons.cpp \
		moc_dart.cpp \
		moc_io.cpp \
		moc_preferences.cpp \
		moc_results.cpp \
		moc_highscores.cpp \
		moc_about.cpp
OBJECTS       = dart.o \
		io.o \
		main.o \
		qtwin.o \
		preferences.o \
		results.o \
		highscores.o \
		about.o \
		qrc_icons.o \
		moc_dart.o \
		moc_io.o \
		moc_preferences.o \
		moc_results.o \
		moc_highscores.o \
		moc_about.o
DIST          = /usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf \
		QeoDart.pro cpp/dart.cpp \
		cpp/io.cpp \
		cpp/main.cpp \
		cpp/qtwin.cpp \
		cpp/preferences.cpp \
		cpp/results.cpp \
		cpp/highscores.cpp \
		cpp/about.cpp
QMAKE_TARGET  = qeodart
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = qeodart


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainWindow.h ui_resultWindow.h ui_preferences.h ui_highscore.h ui_about.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: QeoDart.pro /usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/shell-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf \
		QeoDart.pro \
		icons.qrc \
		/usr/lib/i386-linux-gnu/libQt5Widgets.prl \
		/usr/lib/i386-linux-gnu/libQt5Gui.prl \
		/usr/lib/i386-linux-gnu/libQt5Core.prl \
		/usr/lib/i386-linux-gnu/libQt5Xml.prl
	$(QMAKE) -o Makefile QeoDart.pro
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/shell-unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/spec_post.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/i386-linux-gnu/qt5/mkspecs/features/lex.prf:
QeoDart.pro:
icons.qrc:
/usr/lib/i386-linux-gnu/libQt5Widgets.prl:
/usr/lib/i386-linux-gnu/libQt5Gui.prl:
/usr/lib/i386-linux-gnu/libQt5Core.prl:
/usr/lib/i386-linux-gnu/libQt5Xml.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile QeoDart.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/qeodart1.0.0 || mkdir -p .tmp/qeodart1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/qeodart1.0.0/ && $(COPY_FILE) --parents icons.qrc .tmp/qeodart1.0.0/ && $(COPY_FILE) --parents cpp/dart.hpp cpp/io.hpp cpp/myLabels.hpp cpp/qtwin.h cpp/preferences.hpp cpp/results.hpp cpp/highscores.hpp cpp/about.hpp .tmp/qeodart1.0.0/ && $(COPY_FILE) --parents cpp/dart.cpp cpp/io.cpp cpp/main.cpp cpp/qtwin.cpp cpp/preferences.cpp cpp/results.cpp cpp/highscores.cpp cpp/about.cpp .tmp/qeodart1.0.0/ && $(COPY_FILE) --parents ui/mainWindow.ui ui/resultWindow.ui ui/preferences.ui ui/highscore.ui ui/about.ui .tmp/qeodart1.0.0/ && $(COPY_FILE) --parents lang/de.ts lang/la.ts lang/en.ts .tmp/qeodart1.0.0/ && (cd `dirname .tmp/qeodart1.0.0` && $(TAR) qeodart1.0.0.tar qeodart1.0.0 && $(COMPRESS) qeodart1.0.0.tar) && $(MOVE) `dirname .tmp/qeodart1.0.0`/qeodart1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qeodart1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_icons.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_icons.cpp
qrc_icons.cpp: icons.qrc \
		icons/cursor.png \
		icons/16x16/qeodart.png \
		icons/64x64/qeodart.png \
		icons/90x90/qeodart.png \
		icons/200x200/qeodart.png \
		icons/48x48/qeodart.png \
		icons/256x256/qeodart.png \
		icons/oxygen/show-menu.png \
		icons/oxygen/document-new.png \
		icons/oxygen/network-workgroup.png \
		icons/oxygen/window-close.png \
		icons/oxygen/index.theme \
		icons/oxygen/help-about.png \
		icons/oxygen/list-add.png \
		icons/oxygen/system-users.png \
		icons/oxygen/player-time.png \
		icons/oxygen/edit-find.png \
		icons/oxygen/tools-report-bug.png \
		icons/oxygen/application-exit.png \
		icons/oxygen/edit-clear.png \
		icons/oxygen/games-highscores.png \
		icons/oxygen/zoom-original.png \
		icons/oxygen/games-hint.png \
		icons/oxygen/configure.png \
		icons/oxygen/user-identity.png
	/usr/lib/i386-linux-gnu/qt5/bin/rcc -name icons icons.qrc -o qrc_icons.cpp

compiler_moc_header_make_all: moc_dart.cpp moc_io.cpp moc_preferences.cpp moc_results.cpp moc_highscores.cpp moc_about.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dart.cpp moc_io.cpp moc_preferences.cpp moc_results.cpp moc_highscores.cpp moc_about.cpp
moc_dart.cpp: ui_mainWindow.h \
		cpp/io.hpp \
		cpp/highscores.hpp \
		cpp/dart.hpp \
		cpp/about.hpp \
		ui_about.h \
		cpp/results.hpp \
		ui_resultWindow.h \
		cpp/preferences.hpp \
		ui_preferences.h \
		cpp/myLabels.hpp \
		ui_highscore.h \
		cpp/dart.hpp
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/markus/Dokumente/GitHub/QeoDart -I/home/markus/Dokumente/GitHub/QeoDart -I/home/markus/Dokumente/GitHub/QeoDart/cpp -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtXml -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/i386-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/i686-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/4.9/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include cpp/dart.hpp -o moc_dart.cpp

moc_io.cpp: cpp/io.hpp
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/markus/Dokumente/GitHub/QeoDart -I/home/markus/Dokumente/GitHub/QeoDart -I/home/markus/Dokumente/GitHub/QeoDart/cpp -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtXml -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/i386-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/i686-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/4.9/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include cpp/io.hpp -o moc_io.cpp

moc_preferences.cpp: ui_preferences.h \
		cpp/dart.hpp \
		ui_mainWindow.h \
		cpp/io.hpp \
		cpp/highscores.hpp \
		ui_highscore.h \
		cpp/about.hpp \
		ui_about.h \
		cpp/results.hpp \
		ui_resultWindow.h \
		cpp/preferences.hpp \
		cpp/myLabels.hpp \
		cpp/preferences.hpp
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/markus/Dokumente/GitHub/QeoDart -I/home/markus/Dokumente/GitHub/QeoDart -I/home/markus/Dokumente/GitHub/QeoDart/cpp -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtXml -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/i386-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/i686-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/4.9/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include cpp/preferences.hpp -o moc_preferences.cpp

moc_results.cpp: ui_resultWindow.h \
		cpp/dart.hpp \
		ui_mainWindow.h \
		cpp/io.hpp \
		cpp/highscores.hpp \
		ui_highscore.h \
		cpp/about.hpp \
		ui_about.h \
		cpp/results.hpp \
		cpp/preferences.hpp \
		ui_preferences.h \
		cpp/myLabels.hpp \
		cpp/results.hpp
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/markus/Dokumente/GitHub/QeoDart -I/home/markus/Dokumente/GitHub/QeoDart -I/home/markus/Dokumente/GitHub/QeoDart/cpp -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtXml -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/i386-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/i686-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/4.9/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include cpp/results.hpp -o moc_results.cpp

moc_highscores.cpp: cpp/dart.hpp \
		ui_mainWindow.h \
		cpp/io.hpp \
		cpp/highscores.hpp \
		ui_highscore.h \
		cpp/about.hpp \
		ui_about.h \
		cpp/results.hpp \
		ui_resultWindow.h \
		cpp/preferences.hpp \
		ui_preferences.h \
		cpp/myLabels.hpp \
		cpp/highscores.hpp
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/markus/Dokumente/GitHub/QeoDart -I/home/markus/Dokumente/GitHub/QeoDart -I/home/markus/Dokumente/GitHub/QeoDart/cpp -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtXml -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/i386-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/i686-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/4.9/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include cpp/highscores.hpp -o moc_highscores.cpp

moc_about.cpp: cpp/dart.hpp \
		ui_mainWindow.h \
		cpp/io.hpp \
		cpp/highscores.hpp \
		ui_highscore.h \
		cpp/about.hpp \
		ui_about.h \
		cpp/results.hpp \
		ui_resultWindow.h \
		cpp/preferences.hpp \
		ui_preferences.h \
		cpp/myLabels.hpp \
		cpp/about.hpp
	/usr/lib/i386-linux-gnu/qt5/bin/moc $(DEFINES) -I/usr/lib/i386-linux-gnu/qt5/mkspecs/linux-g++ -I/home/markus/Dokumente/GitHub/QeoDart -I/home/markus/Dokumente/GitHub/QeoDart -I/home/markus/Dokumente/GitHub/QeoDart/cpp -I/usr/include/i386-linux-gnu/qt5 -I/usr/include/i386-linux-gnu/qt5/QtWidgets -I/usr/include/i386-linux-gnu/qt5/QtXml -I/usr/include/i386-linux-gnu/qt5/QtGui -I/usr/include/i386-linux-gnu/qt5/QtCore -I/usr/include/c++/4.9 -I/usr/include/i386-linux-gnu/c++/4.9 -I/usr/include/c++/4.9/backward -I/usr/lib/gcc/i686-linux-gnu/4.9/include -I/usr/local/include -I/usr/lib/gcc/i686-linux-gnu/4.9/include-fixed -I/usr/include/i386-linux-gnu -I/usr/include cpp/about.hpp -o moc_about.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainWindow.h ui_resultWindow.h ui_preferences.h ui_highscore.h ui_about.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainWindow.h ui_resultWindow.h ui_preferences.h ui_highscore.h ui_about.h
ui_mainWindow.h: ui/mainWindow.ui
	/usr/lib/i386-linux-gnu/qt5/bin/uic ui/mainWindow.ui -o ui_mainWindow.h

ui_resultWindow.h: ui/resultWindow.ui
	/usr/lib/i386-linux-gnu/qt5/bin/uic ui/resultWindow.ui -o ui_resultWindow.h

ui_preferences.h: ui/preferences.ui
	/usr/lib/i386-linux-gnu/qt5/bin/uic ui/preferences.ui -o ui_preferences.h

ui_highscore.h: ui/highscore.ui
	/usr/lib/i386-linux-gnu/qt5/bin/uic ui/highscore.ui -o ui_highscore.h

ui_about.h: ui/about.ui
	/usr/lib/i386-linux-gnu/qt5/bin/uic ui/about.ui -o ui_about.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

dart.o: cpp/dart.cpp cpp/dart.hpp \
		ui_mainWindow.h \
		cpp/io.hpp \
		cpp/highscores.hpp \
		ui_highscore.h \
		cpp/about.hpp \
		ui_about.h \
		cpp/results.hpp \
		ui_resultWindow.h \
		cpp/preferences.hpp \
		ui_preferences.h \
		cpp/myLabels.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dart.o cpp/dart.cpp

io.o: cpp/io.cpp cpp/dart.hpp \
		ui_mainWindow.h \
		cpp/io.hpp \
		cpp/highscores.hpp \
		ui_highscore.h \
		cpp/about.hpp \
		ui_about.h \
		cpp/results.hpp \
		ui_resultWindow.h \
		cpp/preferences.hpp \
		ui_preferences.h \
		cpp/myLabels.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o io.o cpp/io.cpp

main.o: cpp/main.cpp cpp/dart.hpp \
		ui_mainWindow.h \
		cpp/io.hpp \
		cpp/highscores.hpp \
		ui_highscore.h \
		cpp/about.hpp \
		ui_about.h \
		cpp/results.hpp \
		ui_resultWindow.h \
		cpp/preferences.hpp \
		ui_preferences.h \
		cpp/myLabels.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o cpp/main.cpp

qtwin.o: cpp/qtwin.cpp cpp/qtwin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qtwin.o cpp/qtwin.cpp

preferences.o: cpp/preferences.cpp cpp/preferences.hpp \
		ui_preferences.h \
		cpp/dart.hpp \
		ui_mainWindow.h \
		cpp/io.hpp \
		cpp/highscores.hpp \
		ui_highscore.h \
		cpp/about.hpp \
		ui_about.h \
		cpp/results.hpp \
		ui_resultWindow.h \
		cpp/myLabels.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preferences.o cpp/preferences.cpp

results.o: cpp/results.cpp cpp/results.hpp \
		ui_resultWindow.h \
		cpp/dart.hpp \
		ui_mainWindow.h \
		cpp/io.hpp \
		cpp/highscores.hpp \
		ui_highscore.h \
		cpp/about.hpp \
		ui_about.h \
		cpp/preferences.hpp \
		ui_preferences.h \
		cpp/myLabels.hpp \
		cpp/qtwin.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o results.o cpp/results.cpp

highscores.o: cpp/highscores.cpp cpp/highscores.hpp \
		cpp/dart.hpp \
		ui_mainWindow.h \
		cpp/io.hpp \
		cpp/about.hpp \
		ui_about.h \
		cpp/results.hpp \
		ui_resultWindow.h \
		cpp/preferences.hpp \
		ui_preferences.h \
		cpp/myLabels.hpp \
		ui_highscore.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o highscores.o cpp/highscores.cpp

about.o: cpp/about.cpp cpp/about.hpp \
		cpp/dart.hpp \
		ui_mainWindow.h \
		cpp/io.hpp \
		cpp/highscores.hpp \
		ui_highscore.h \
		cpp/results.hpp \
		ui_resultWindow.h \
		cpp/preferences.hpp \
		ui_preferences.h \
		cpp/myLabels.hpp \
		ui_about.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o about.o cpp/about.cpp

qrc_icons.o: qrc_icons.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_icons.o qrc_icons.cpp

moc_dart.o: moc_dart.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dart.o moc_dart.cpp

moc_io.o: moc_io.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_io.o moc_io.cpp

moc_preferences.o: moc_preferences.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_preferences.o moc_preferences.cpp

moc_results.o: moc_results.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_results.o moc_results.cpp

moc_highscores.o: moc_highscores.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_highscores.o moc_highscores.cpp

moc_about.o: moc_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_about.o moc_about.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/bin || mkdir -p $(INSTALL_ROOT)/usr/bin
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(STRIP) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/usr/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/bin/ 


install_langfiles: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/QeoDart/lang || mkdir -p $(INSTALL_ROOT)/usr/share/QeoDart/lang
	-$(INSTALL_FILE) /home/markus/Dokumente/GitHub/QeoDart/lang/de.qm $(INSTALL_ROOT)/usr/share/QeoDart/lang/
	-$(INSTALL_FILE) /home/markus/Dokumente/GitHub/QeoDart/lang/en.qm $(INSTALL_ROOT)/usr/share/QeoDart/lang/
	-$(INSTALL_FILE) /home/markus/Dokumente/GitHub/QeoDart/lang/fr.qm $(INSTALL_ROOT)/usr/share/QeoDart/lang/
	-$(INSTALL_FILE) /home/markus/Dokumente/GitHub/QeoDart/lang/la.qm $(INSTALL_ROOT)/usr/share/QeoDart/lang/
	-$(INSTALL_FILE) /home/markus/Dokumente/GitHub/QeoDart/lang/qt_de.qm $(INSTALL_ROOT)/usr/share/QeoDart/lang/
	-$(INSTALL_FILE) /home/markus/Dokumente/GitHub/QeoDart/lang/qt_fr.qm $(INSTALL_ROOT)/usr/share/QeoDart/lang/

uninstall_langfiles: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/QeoDart/lang/qt_fr.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/QeoDart/lang/qt_de.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/QeoDart/lang/la.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/QeoDart/lang/fr.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/QeoDart/lang/en.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/QeoDart/lang/de.qm
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/QeoDart/lang/ 


install_qcf: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/QeoDart/qcf || mkdir -p $(INSTALL_ROOT)/usr/share/QeoDart/qcf
	-$(INSTALL_DIR) /home/markus/Dokumente/GitHub/QeoDart/qcf/br $(INSTALL_ROOT)/usr/share/QeoDart/qcf/
	-$(INSTALL_FILE) /home/markus/Dokumente/GitHub/QeoDart/qcf/br.qcfx $(INSTALL_ROOT)/usr/share/QeoDart/qcf/
	-$(INSTALL_DIR) /home/markus/Dokumente/GitHub/QeoDart/qcf/de $(INSTALL_ROOT)/usr/share/QeoDart/qcf/
	-$(INSTALL_FILE) /home/markus/Dokumente/GitHub/QeoDart/qcf/de.qcfx $(INSTALL_ROOT)/usr/share/QeoDart/qcf/
	-$(INSTALL_FILE) /home/markus/Dokumente/GitHub/QeoDart/qcf/de1.qcfx $(INSTALL_ROOT)/usr/share/QeoDart/qcf/
	-$(INSTALL_DIR) /home/markus/Dokumente/GitHub/QeoDart/qcf/eu $(INSTALL_ROOT)/usr/share/QeoDart/qcf/
	-$(INSTALL_FILE) /home/markus/Dokumente/GitHub/QeoDart/qcf/eu.qcfx $(INSTALL_ROOT)/usr/share/QeoDart/qcf/
	-$(INSTALL_DIR) /home/markus/Dokumente/GitHub/QeoDart/qcf/in $(INSTALL_ROOT)/usr/share/QeoDart/qcf/
	-$(INSTALL_FILE) /home/markus/Dokumente/GitHub/QeoDart/qcf/in.qcfx $(INSTALL_ROOT)/usr/share/QeoDart/qcf/
	-$(INSTALL_DIR) /home/markus/Dokumente/GitHub/QeoDart/qcf/nrw $(INSTALL_ROOT)/usr/share/QeoDart/qcf/
	-$(INSTALL_FILE) /home/markus/Dokumente/GitHub/QeoDart/qcf/nrw.qcfx $(INSTALL_ROOT)/usr/share/QeoDart/qcf/
	-$(INSTALL_FILE) /home/markus/Dokumente/GitHub/QeoDart/qcf/wikipedianames $(INSTALL_ROOT)/usr/share/QeoDart/qcf/

uninstall_qcf: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/QeoDart/qcf/wikipedianames
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/QeoDart/qcf/nrw.qcfx
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/QeoDart/qcf/nrw
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/QeoDart/qcf/in.qcfx
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/QeoDart/qcf/in
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/QeoDart/qcf/eu.qcfx
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/QeoDart/qcf/eu
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/QeoDart/qcf/de1.qcfx
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/QeoDart/qcf/de.qcfx
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/QeoDart/qcf/de
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/QeoDart/qcf/br.qcfx
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/QeoDart/qcf/br
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/QeoDart/qcf/ 


install_icon: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/icons/hicolor/scalable/apps || mkdir -p $(INSTALL_ROOT)/usr/share/icons/hicolor/scalable/apps
	-$(INSTALL_FILE) /home/markus/Dokumente/GitHub/QeoDart/icons/qeodart.svg $(INSTALL_ROOT)/usr/share/icons/hicolor/scalable/apps/

uninstall_icon: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/scalable/apps/qeodart.svg
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/scalable/apps/ 


install_icon256: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/icons/hicolor/256x256/apps || mkdir -p $(INSTALL_ROOT)/usr/share/icons/hicolor/256x256/apps
	-$(INSTALL_FILE) /home/markus/Dokumente/GitHub/QeoDart/icons/256x256/qeodart.png $(INSTALL_ROOT)/usr/share/icons/hicolor/256x256/apps/

uninstall_icon256: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/256x256/apps/qeodart.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/256x256/apps/ 


install_icon48: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/apps || mkdir -p $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/apps
	-$(INSTALL_FILE) /home/markus/Dokumente/GitHub/QeoDart/icons/48x48/qeodart.png $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/apps/

uninstall_icon48: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/apps/qeodart.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/48x48/apps/ 


install_icon16: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/icons/hicolor/16x16/apps || mkdir -p $(INSTALL_ROOT)/usr/share/icons/hicolor/16x16/apps
	-$(INSTALL_FILE) /home/markus/Dokumente/GitHub/QeoDart/icons/16x16/qeodart.png $(INSTALL_ROOT)/usr/share/icons/hicolor/16x16/apps/

uninstall_icon16: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/icons/hicolor/16x16/apps/qeodart.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/icons/hicolor/16x16/apps/ 


install_desktop: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/applications || mkdir -p $(INSTALL_ROOT)/usr/share/applications
	-$(INSTALL_FILE) /home/markus/Dokumente/GitHub/QeoDart/QeoDart.desktop $(INSTALL_ROOT)/usr/share/applications/

uninstall_desktop: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/QeoDart.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install:  install_target install_langfiles install_qcf install_icon install_icon256 install_icon48 install_icon16 install_desktop  FORCE

uninstall: uninstall_target uninstall_langfiles uninstall_qcf uninstall_icon uninstall_icon256 uninstall_icon48 uninstall_icon16 uninstall_desktop   FORCE

FORCE:

