######################################################################
# Automatically generated by qmake (2.01a) Sa. Jul 16 17:34:06 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . cpp ui
INCLUDEPATH += . cpp

# Input
HEADERS += cpp/dart.hpp
FORMS += ui/mainWindow.ui
SOURCES += cpp/dart.cpp cpp/main.cpp
